paths:
  swagger: /Users/talalmos/Documents/Code/Projects/Mock_JSON/data/swagger
  examples: /Users/talalmos/Documents/Code/Projects/Mock_JSON/data/examples
  output: /Users/talalmos/Documents/Code/Projects/Mock_JSON/data/mock_output
preserve_fields:
  - status
  - message
  - transId
  - entity
  - id
  - requiredRenewal
  - isExpired
  - isActive
  - isSmart
  - isKlasi
  - isRiziko
  - isCopyPolicyDoc
  - isPaila
  - isIndependent
  - isNew
  - sign
  - eSite
  - totalPayments
  - paymentNo
  - yieldBeginningYear
  - lastDeposit
  - depositedThisYear
  - availableWithdraw
  - withdrawDate
  - yieldFromYearBeginningTotal
  - fromDeposit
  - fromSaving
  - yieldUpdateDate
  - dailyYieldUpdateDate
  - hasProfitsShare
  - updateTo
  - dailyUpdateTo
  - tsuotPopup 